"""Generate the blank. This is what closes the gap between "an agent can write
a parser" and "an agent knows what to feed the engine": it doesn't have to
invent the shape, it fills in a form the engine wrote."""

from __future__ import annotations

import re
from pathlib import Path

PLUGIN = '''"""Parser for {name}.

Contract:
  * return a ParseResult holding a Polars DataFrame
  * bad rows go into `rejects` with a `_reject_reason` column -- never raise
  * add `_src_line_no` so a rejected row can be traced to its line
  * do NOT open files, touch Iceberg, or import anything from ffe.io
"""

from __future__ import annotations

import polars as pl

from ffe.core.plugins import ParseContext, ParserPlugin, register
from ffe.core.report import ParseResult


@register("{ref}")
class {cls}(ParserPlugin):
    def parse(self, raw: bytes, ctx: ParseContext) -> ParseResult:
        lines = raw.decode("utf-8", errors="replace").splitlines()

        rows, bad = [], []
        for lineno, text in enumerate(lines, start=1):
            if not text.strip():
                continue
            # TODO: replace this with the real logic for {name}
            raise NotImplementedError("implement parse() for {name}")

        frame = pl.DataFrame(rows) if rows else pl.DataFrame()
        rejects = pl.DataFrame(bad) if bad else None
        return ParseResult(frame=frame, rejects=rejects)
'''

TEST = '''"""Generated by `ffe new-parser {ref}`. The sample is the regression test."""

from pathlib import Path

import pytest

from ffe.core.engine import parse
from ffe.core.plugins import load_dir
from ffe.core.spec import PluginParser

FIXTURE = Path(__file__).parent / "fixtures" / "{stem}.txt"


@pytest.fixture(scope="module", autouse=True)
def _plugins():
    load_dir(Path(__file__).parent.parent / "plugins")


def test_{stem}_parses():
    assert FIXTURE.exists(), f"drop your 100-row sample at {{FIXTURE}}"
    result = parse(PluginParser(ref="{ref}"), FIXTURE.read_bytes())

    # TODO: tighten these once you know what the file should produce
    assert len(result.frame) > 0
    assert result.frame.columns
'''

FEED = """name: {ref}
source:
  pattern: "data/{stem}/*.zip"      # TODO: where the files actually arrive
  members: "*"
parser:
  kind: plugin
  ref: {ref}
  options: {{}}
target:
  table: bronze.{stem}
policy:
  on_reject: quarantine
  max_reject_ratio: 0.01
"""


def _ident(ref: str) -> tuple[str, str]:
    stem = re.sub(r"[^a-z0-9]+", "_", ref.lower()).strip("_")
    cls = "".join(part.capitalize() for part in stem.split("_"))
    return stem, cls


def new_parser(ref: str, root: Path) -> dict[str, str]:
    stem, cls = _ident(ref)
    targets = {
        "plugin": root / "plugins" / f"{stem}.py",
        "test": root / "tests" / f"test_{stem}.py",
        "feed": root / "feeds" / f"{ref}.yaml",
    }
    bodies = {
        "plugin": PLUGIN.format(name=ref, ref=ref, cls=cls),
        "test": TEST.format(ref=ref, stem=stem),
        "feed": FEED.format(ref=ref, stem=stem),
    }
    written = {}
    for key, path in targets.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        if path.exists():
            written[key] = f"{path} (exists, left alone)"
            continue
        path.write_text(bodies[key])
        written[key] = str(path)
    written["fixture"] = str(root / "tests" / "fixtures" / f"{stem}.txt")
    return written
