"""Generated by `ffe new-parser msci-test`. The sample is the regression test."""

from pathlib import Path

import pytest

from ffe.core.engine import parse
from ffe.core.plugins import load_dir
from ffe.core.spec import PluginParser

FIXTURE = Path(__file__).parent / "fixtures" / "msci_test.txt"


@pytest.fixture(scope="module", autouse=True)
def _plugins():
    load_dir(Path(__file__).parent.parent / "plugins")


def test_msci_test_parses():
    assert FIXTURE.exists(), f"drop your 100-row sample at {FIXTURE}"
    result = parse(PluginParser(ref="msci-test"), FIXTURE.read_bytes())

    assert result.frame.columns == [
        "Sector_ID",
        "Industry_Group_ID",
        "Industry_ID",
        "Sub_Industry_ID",
        "Label_EN",
        "Label_FR",
        "_src_line_no",
    ]
    assert all(
        str(d) == "String"
        for n, d in result.frame.schema.items()
        if n != "_src_line_no"
    )
    assert str(result.frame.schema["_src_line_no"]) == "UInt32"

    assert len(result.frame) == 5
    assert result.frame["Sector_ID"].to_list() == ["10", "10", "20", "45", "45"]
    assert result.frame["Sub_Industry_ID"].to_list() == [
        "10101010",
        "10102010",
        "20101010",
        "45103020",
        "45201020",
    ]
    assert result.frame["Label_EN"].to_list() == [
        "Energy (Oil & Gas)",
        "Oil, Gas & Consumable Fuels",
        "Aerospace & Defense",
        "Systems Software",
        "Communications Equipment",
    ]
    assert result.frame["Label_FR"].to_list() == [
        "Énergie",
        "Combustibles",
        "Aérospatiale",
        "Logiciels Systèmes",
        "Équipement de Comms",
    ]
    assert result.frame["_src_line_no"].to_list() == [8, 9, 10, 11, 12]

    assert result.rejects is None
    assert result.report.rows_parsed == 5
    assert result.report.rows_rejected == 0
    assert result.report.trailer_declared_rows == 5
    assert result.report.trailer_seen is True
