"""Generated by `ffe new-parser msci-test`. The sample is the regression test."""

from datetime import date
from pathlib import Path

import pytest

from ffe.core.engine import parse
from ffe.core.plugins import ParseContext, load_dir
from ffe.core.spec import PluginParser

FIXTURE = Path(__file__).parent / "fixtures" / "msci_test.txt"


@pytest.fixture(scope="module", autouse=True)
def _plugins():
    load_dir(Path(__file__).parent.parent / "plugins")


def test_msci_test_parses():
    assert FIXTURE.exists(), f"drop your 100-row sample at {FIXTURE}"
    result = parse(PluginParser(ref="msci-test"), FIXTURE.read_bytes())

    assert result.frame.columns == [
        "Sector_ID",
        "Industry_Group_ID",
        "Industry_ID",
        "Sub_Industry_ID",
        "Label_EN",
        "Label_FR",
        "_src_line_no",
        "business_date",
    ]
    assert all(
        str(d) == "String"
        for n, d in result.frame.schema.items()
        if n not in ("_src_line_no", "business_date")
    )
    assert str(result.frame.schema["_src_line_no"]) == "UInt32"

    assert len(result.frame) == 5
    assert result.frame["Sector_ID"].to_list() == ["10", "10", "20", "45", "45"]
    assert result.frame["Sub_Industry_ID"].to_list() == [
        "10101010",
        "10102010",
        "20101010",
        "45103020",
        "45201020",
    ]
    assert result.frame["Label_EN"].to_list() == [
        "Energy (Oil & Gas)",
        "Oil, Gas & Consumable Fuels",
        "Aerospace & Defense",
        "Systems Software",
        "Communications Equipment",
    ]
    assert result.frame["Label_FR"].to_list() == [
        "Énergie",
        "Combustibles",
        "Aérospatiale",
        "Logiciels Systèmes",
        "Équipement de Comms",
    ]
    assert result.frame["_src_line_no"].to_list() == [8, 9, 10, 11, 12]

    assert result.rejects is None
    assert result.report.rows_parsed == 5
    assert result.report.rows_rejected == 0
    assert result.report.trailer_declared_rows == 5
    assert result.report.trailer_seen is True


def test_business_date_comes_from_the_generated_comment():
    """One archive is one business day; the file states it, so read it."""
    result = parse(PluginParser(ref="msci-test"), FIXTURE.read_bytes())
    assert str(result.frame.schema["business_date"]) == "Date"
    assert result.frame["business_date"].to_list() == [date(2026, 8, 23)] * 5


def test_a_run_option_overrides_the_date_in_the_file():
    """--option business_date=... is how a backfill corrects a drop."""
    result = parse(
        PluginParser(ref="msci-test"),
        FIXTURE.read_bytes(),
        ParseContext(options={"business_date": "2020-01-01"}),
    )
    assert result.frame["business_date"].to_list() == [date(2020, 1, 1)] * 5


def test_an_unparseable_date_is_null_not_a_crash():
    """A wrong date is worse than none, and all_null_columns will show it."""
    result = parse(
        PluginParser(ref="msci-test"),
        FIXTURE.read_bytes(),
        ParseContext(options={"business_date": "not-a-date"}),
    )
    assert result.frame["business_date"].to_list() == [None] * 5


def test_spec_options_are_the_default_and_a_run_option_wins():
    """engine merges {**spec.options, **ctx.options} -- per-run beats per-spec."""
    spec = PluginParser(ref="msci-test", options={"business_date": "2019-05-05"})
    from_spec = parse(spec, FIXTURE.read_bytes())
    assert from_spec.frame["business_date"][0] == date(2019, 5, 5)

    overridden = parse(
        spec, FIXTURE.read_bytes(), ParseContext(options={"business_date": "2021-07-07"})
    )
    assert overridden.frame["business_date"][0] == date(2021, 7, 7)


def test_plugin_reports_carry_column_stats():
    """Without these `all_null_columns` is vacuous for every plugin feed."""
    result = parse(PluginParser(ref="msci-test"), FIXTURE.read_bytes())
    assert [c.name for c in result.report.columns] == result.frame.columns
    assert all(c.null_count == 0 for c in result.report.columns)
